@extends('layouts.app')

@section('content')
<div class="--background-img">
    <div class="--dark-overlay"></div>
</div>

<div class="container">
    <h1 class="text-center --roboto-condensed --bold mb-3" >Service Fees</h1>
    <div class="text-justify">
        <section id="repair-section" class="mb-5">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium modi, facere consequatur necessitatibus, molestias illum pariatur suscipit quasi magnam, voluptatibus nobis dolore beatae quae blanditiis quod. Natus ab voluptate pariatur blanditiis autem libero sed nobis hic dolore laborum officia sequi optio reiciendis debitis magni, porro accusamus! Voluptates, sint? Debitis, vitae. Repellat nesciunt ducimus nam est repudiandae ex repellendus! Aspernatur facere sunt rem voluptatibus odit tenetur, consequuntur quas cum modi enim aut debitis maxime esse recusandae ab ducimus autem ipsum. Quaerat ratione earum minus nesciunt vel reprehenderit neque sapiente iure sequi beatae, mollitia autem fugit deleniti molestiae aspernatur quibusdam eligendi et vero tempore obcaecati dolor quisquam! Delectus sunt, placeat, nisi commodi expedita debitis deleniti labore quia eligendi fugit aperiam provident eos facilis ut harum! Cumque nulla aliquam quisquam est illum, qui autem optio sapiente, impedit expedita deleniti id quae porro! Nostrum, quae perspiciatis nulla praesentium magnam nesciunt obcaecati possimus fugiat, placeat voluptatum corporis iure aut iste perferendis laborum quaerat, ipsam ratione omnis? Hic inventore eveniet, sequi sit porro accusantium minus, modi laborum, cumque molestias iste! Neque corporis at, dolorum quas commodi perferendis molestias perspiciatis beatae placeat voluptatibus qui ratione libero odio minus nobis repudiandae optio, mollitia ea ipsa aspernatur. Dolorum, omnis.</p>
        </section>

        <section id="upgrade-section" class="mb-5">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium modi, facere consequatur necessitatibus, molestias illum pariatur suscipit quasi magnam, voluptatibus nobis dolore beatae quae blanditiis quod. Natus ab voluptate pariatur blanditiis autem libero sed nobis hic dolore laborum officia sequi optio reiciendis debitis magni, porro accusamus! Voluptates, sint? Debitis, vitae. Repellat nesciunt ducimus nam est repudiandae ex repellendus! Aspernatur facere sunt rem voluptatibus odit tenetur, consequuntur quas cum modi enim aut debitis maxime esse recusandae ab ducimus autem ipsum. Quaerat ratione earum minus nesciunt vel reprehenderit neque sapiente iure sequi beatae, mollitia autem fugit deleniti molestiae aspernatur quibusdam eligendi et vero tempore obcaecati dolor quisquam! Delectus sunt, placeat, nisi commodi expedita debitis deleniti labore quia eligendi fugit aperiam provident eos facilis ut harum! Cumque nulla aliquam quisquam est illum, qui autem optio sapiente, impedit expedita deleniti id quae porro! Nostrum, quae perspiciatis nulla praesentium magnam nesciunt obcaecati possimus fugiat, placeat voluptatum corporis iure aut iste perferendis laborum quaerat, ipsam ratione omnis? Hic inventore eveniet, sequi sit porro accusantium minus, modi laborum, cumque molestias iste! Neque corporis at, dolorum quas commodi perferendis molestias perspiciatis beatae placeat voluptatibus qui ratione libero odio minus nobis repudiandae optio, mollitia ea ipsa aspernatur. Dolorum, omnis.</p>
        </section>

        <section id="print-section" class="mb-5">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium modi, facere consequatur necessitatibus, molestias illum pariatur suscipit quasi magnam, voluptatibus nobis dolore beatae quae blanditiis quod. Natus ab voluptate pariatur blanditiis autem libero sed nobis hic dolore laborum officia sequi optio reiciendis debitis magni, porro accusamus! Voluptates, sint? Debitis, vitae. Repellat nesciunt ducimus nam est repudiandae ex repellendus! Aspernatur facere sunt rem voluptatibus odit tenetur, consequuntur quas cum modi enim aut debitis maxime esse recusandae ab ducimus autem ipsum. Quaerat ratione earum minus nesciunt vel reprehenderit neque sapiente iure sequi beatae, mollitia autem fugit deleniti molestiae aspernatur quibusdam eligendi et vero tempore obcaecati dolor quisquam! Delectus sunt, placeat, nisi commodi expedita debitis deleniti labore quia eligendi fugit aperiam provident eos facilis ut harum! Cumque nulla aliquam quisquam est illum, qui autem optio sapiente, impedit expedita deleniti id quae porro! Nostrum, quae perspiciatis nulla praesentium magnam nesciunt obcaecati possimus fugiat, placeat voluptatum corporis iure aut iste perferendis laborum quaerat, ipsam ratione omnis? Hic inventore eveniet, sequi sit porro accusantium minus, modi laborum, cumque molestias iste! Neque corporis at, dolorum quas commodi perferendis molestias perspiciatis beatae placeat voluptatibus qui ratione libero odio minus nobis repudiandae optio, mollitia ea ipsa aspernatur. Dolorum, omnis.</p>
        </section>
    </div>
</div>
@endsection